[0m16:41:48.777440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002438F59CE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002438F13DAC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243920ED5B0>]}


============================== 16:41:48.883861 | 888b93c6-5eab-4fa4-90ff-dd550d7f4348 ==============================
[0m16:41:48.883861 [info ] [MainThread]: Running with dbt=1.10.3
[0m16:41:48.884981 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Bright MEHOU\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init jaffle_shop', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:41:49.273047 [debug] [MainThread]: Starter project path: C:\dbt-tutorial\.venv\Lib\site-packages\dbt\include\starter_project
[0m16:41:49.321877 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:41:49.321877 [info ] [MainThread]: Setting up your profile.
[0m16:41:49.324830 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m16:41:49.328658 [debug] [MainThread]: Command `dbt init` failed at 16:41:49.328658 after 0.71 seconds
[0m16:41:49.328658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024392984F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243925C3440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243925C34D0>]}
[0m16:41:49.328658 [debug] [MainThread]: Flushing usage events
[0m16:41:49.737765 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:20:26.838859 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269922BFDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026995E27F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026995E26BA0>]}


============================== 21:20:26.852582 | de873f50-d559-4af6-96ab-fe37e93ef5fc ==============================
[0m21:20:26.852582 [info ] [MainThread]: Running with dbt=1.10.3
[0m21:20:26.854092 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Bright MEHOU\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:20:26.854092 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:20:26.856082 [debug] [MainThread]: Command `dbt test` failed at 21:20:26.856082 after 0.45 seconds
[0m21:20:26.857837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026995A07D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026995E27F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269970BB2C0>]}
[0m21:20:26.857837 [debug] [MainThread]: Flushing usage events
[0m21:20:27.260597 [debug] [MainThread]: An error was encountered while trying to flush usage events
